# Generated by Django 3.0.2 on 2020-01-23 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
